services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # web:
  #   build: .
  #   # Rodando o Django direto pelo Python do container
  #   command: python manage.py runserver 0.0.0.0:19003
  #   volumes:
  #     - .:/app
  #     - /app/.venv
  #   ports:
  #     - "19003:19003"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data: