[project]
name = "fabricaHub_backEnd"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Fabrica", email = "fabricadesoftware.araquari@ifc.edu.br"},
]
dependencies = ["django>=6.0.5", "python-dotenv>=1.2.2", "netifaces>=0.11.0", "djangorestframework>=3.17.1", "djangorestframework-simplejwt>=5.5.1", "django-cors-headers>=4.9.0", "psycopg2-binary>=2.9.12", "django-filter>=25.2"]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
migrate = { cmd = "python manage.py migrate" }
dev = { cmd = "python manage.py runserver 0.0.0.0:${PORT}", env_file = ".env" }