# Generated by Django 6.0.5 on 2026-05-15 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.CharField(max_length=120)),
                ('semestre', models.PositiveIntegerField()),
                ('squad', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('design', 'Design'), ('devops', 'DevOps')], max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao_tecnica', models.TextField()),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planejamento', max_length=30)),
                ('data_inicio', models.DateField()),
                ('prazo_entrega', models.DateField()),
                ('membros', models.ManyToManyField(blank=True, related_name='projetos', to='fabricahub.membro')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['prazo_entrega', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contexto_entrega', models.TextField()),
                ('metrica_entrega', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacao', models.TextField(blank=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='fabricahub.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='fabricahub.projeto')),
            ],
            options={
                'verbose_name': 'Registro de Performance',
                'verbose_name_plural': 'Registros de Performance',
                'ordering': ['-created_at'],
            },
        ),
    ]
