# Generated by Django 6.0.5 on 2026-05-20 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricahub', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoMembro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('papel_no_projeto', models.CharField(max_length=100)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_projetos', to='fabricahub.membro')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto_membros', to='fabricahub.projeto')),
            ],
            options={
                'verbose_name': 'Projeto Membro',
                'verbose_name_plural': 'Projeto Membros',
                'ordering': ['projeto', 'membro'],
            },
        ),
    ]
