# Generated by Django 6.0.5 on 2026-05-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricahub', '0005_logauditoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceLog',
        ),
    ]
