# Generated by Django 6.0.5 on 2026-05-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricahub', '0006_delete_performancelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.IntegerField(choices=[(1, 'Membro'), (2, 'Professor'), (3, 'Techlead')], default=1, verbose_name='Tipo de Usuário'),
        ),
    ]
